name: doctl
version: git
summary: A command line tool for DigitalOcean services
description: doctl is a command line tool for DigitalOcean services using the API.

grade: stable
confinement: strict

build-packages:
  - gcc
  - git

parts:
  go:
    source-tag: go1.11.4
  launcher:
    after: [go]
    source: snap/local
    plugin: dump
    organize:
      '*': bin/
    override-stage: |
      cd $SNAPCRAFT_PART_INSTALL
      chmod +x bin/doctl-launch
      snapcraftctl stage
  doctl:
    after: [launcher]
    source: .
    plugin: go
    go-importpath: github.com/digitalocean/doctl
    go-packages: [github.com/digitalocean/doctl/cmd/doctl]
    override-pull: |
      git clone https://github.com/digitalocean/doctl.git .
    override-build: |
      version=$(scripts/version.sh)
      snapcraftctl set-version ${version}
      GO111MODULE=on go build -mod=vendor -o doctl cmd/doctl/main.go
      chmod +x doctl
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      mv doctl $SNAPCRAFT_PART_INSTALL/bin/
    organize:
      bin/doctl: bin/doctl.real

plugs:
  doctl-config:
    interface: personal-files
    write:
      - $HOME/.config/doctl
  kube-config:
    interface: personal-files
    write:
      - $HOME/.kube/config
      - $HOME/.kube/config.lock

apps:
  doctl:
    command: bin/doctl-launch
    plugs:
      - home
      - network
      - ssh-keys
      - doctl-config
      - kube-config
