name: doctl
version-script: git tag -l | sort --version-sort | tail -n1 | cut -c 2-
version: git
summary: A command line tool for DigitalOcean services
description: doctl is a command line tool for DigitalOcean services using the API.

grade: stable
confinement: strict

build-packages:
  - gcc
  - git

parts:
  go:
    source-tag: go1.11.4
  doctl:
    after: [go]
    source: .
    plugin: go
    go-importpath: github.com/digitalocean/doctl
    go-packages: [github.com/digitalocean/doctl/cmd/doctl]

apps:
  doctl:
    command: bin/doctl
    plugs:
      - home
      - network
      - ssh-keys
